package map.neshan.urlshortener.models;


import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "urls_status")
@Data
public class UrlStatus {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Setter(AccessLevel.NONE)
    @Getter(AccessLevel.NONE)
    /**
     * the id that auto generated by database
     */
    private Long id;

    /**
     * the url that user wants to shorten
     */
    private String url;

    /**
     * the shortened url
     */
    private String shortUrl;

    /**
     * the username of the user who wants to add the url
     */
    private String username;

    /**
     * the number of visits of the url
     */
    private Long visits;

    /**
     * the time of the last visit of the url as timestamp
     */
    private Long lastVisitTime;
}
