package map.neshan.urlshortener.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "users")
@Getter
public class Users {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    /**
     * the id that auto generated by database
     */
    private Long id;

    /**
     * the username of the user who wants to add the url
     */
    private String username;

    /**
     * the password of the user who wants to add the url
     */
    private String password;

}
