package map.neshan.urlshortener.models;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "users")
@Data
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Setter(AccessLevel.NONE)
    @Getter(AccessLevel.NONE)
    /**
     * the id that auto generated by database
     */
    private Long id;

    /**
     * the username of the user who wants to add the url
     */
    private String username;

    /**
     * the password of the user who wants to add the url
     */
    private String password;

}
